const VIEW_SUMMARY = 'VIEW_SUMMARY'
const VIEW_DETAILS = 'VIEW_DETAILS'
const API_ENDPOINT_1 = 'API_ENDPOINT_1'
const API_ENDPOINT_2 = 'API_ENDPOINT_2'

export {
  VIEW_SUMMARY,
  VIEW_DETAILS,
  API_ENDPOINT_1,
  API_ENDPOINT_2
}
